Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.synced_folder "../", "/var/www/portfolio"

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "portfolio-vm"
    vb.memory = 1024
    vb.cpus   = 1
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook       = "playbooks/main.yml"
    ansible.install_mode   = "default"
    ansible.provisioning_path = "/var/www/portfolio/iac"
  end
end
